package com.wemall.shopcategories.dao;

import java.util.List;

import com.wemall.shopcategories.entity.Categories;

public interface CategoriesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    Categories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Categories record);
    
    List<Categories> selectAllCategories();
}